name: Update M3U Playlist

on:
  schedule:
    - cron: '*/15 * * * *' # প্রতি ১৫ মিনিট পর পর চলবে
  workflow_dispatch: # ম্যানুয়ালি চালানোর জন্য

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install requests

      - name: Run update script
        run: python update_m3u.py

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add Test.m3u
          git commit -m "Auto-update playlist" || exit 0
          git push
