name: Update IPTV

on:
  schedule:
    - cron: "*/15 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: Install requests
        run: pip install requests

      - name: Run updater
        run: python update.py

      - name: Auto Push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add Test.m3u
          git commit -m "Auto update"
          git push
