name: STABLE-SPORTS TV Auto Update

on:
  workflow_dispatch:
  schedule:
    # এই ক্রন জবটি প্রতি ১ ঘণ্টা পর পর (ঘণ্টার শুরুতে) অটো-রান করাবে
    - cron: '0 * * * *'

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Python Script
      run: python stablesportstv.py

    - name: Commit and Push Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add *.m3u
        git diff --quiet && git diff --staged --quiet || (git commit -m "Auto Update Playlists $(date)" && git push)
